from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class main_window(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        a = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QLabel"))
        gb_lay.addWidget(QtWidgets.QLabel("This is a Label"))
        a.setLayout(gb_lay)

        b = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QLineEdit"))
        gb_lay.addWidget(QtWidgets.QLineEdit(""))
        b.setLayout(gb_lay)

        c = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QTextEdit"))
        gb_lay.addWidget(QtWidgets.QTextEdit(""))
        c.setLayout(gb_lay)

        d = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QPushButton"))
        gb_lay.addWidget(QtWidgets.QPushButton("PushBotton"))
        d.setLayout(gb_lay)

        e = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QRadioButton"))
        gb_lay.addWidget(QtWidgets.QRadioButton("Item 1"))
        e.setLayout(gb_lay)

        f = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QCheckBox"))
        gb_lay.addWidget(QtWidgets.QCheckBox("Check 1"))
        f.setLayout(gb_lay)

        g = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        Combox = QtWidgets.QComboBox()
        Combox.addItems(["1","2","3"])
        gb_lay.addWidget(QtWidgets.QLabel("This is a QComboBox"))
        gb_lay.addWidget(Combox)
        g.setLayout(gb_lay)

        h = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        Spinbox=QtWidgets.QSpinBox()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QSpinBox"))
        gb_lay.addWidget(Spinbox)
        h.setLayout(gb_lay)

        i = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        Date=QtWidgets.QCalendarWidget()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QCalendarWidget"))
        gb_lay.addWidget(Date)
        i.setLayout(gb_lay)

        j = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        Table=QtWidgets.QTableWidget(1,10)
        gb_lay.addWidget(QtWidgets.QLabel("This is a QTableWidget"))
        gb_lay.addWidget(Table)
        j.setLayout(gb_lay)

        k = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        Slider=QtWidgets.QSlider(QtCore.Qt.Horizontal)
        gb_lay.addWidget(QtWidgets.QLabel("This is a QSlider"))
        gb_lay.addWidget(Slider)
        k.setLayout(gb_lay)

        l = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        ProgressBar=QtWidgets.QProgressBar()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QProgressBar"))
        gb_lay.addWidget(ProgressBar)
        l.setLayout(gb_lay)

        m = QtWidgets.QWidget()
        gb_lay=QtWidgets.QHBoxLayout()
        Dial=QtWidgets.QDial()
        gb_lay.addWidget(QtWidgets.QLabel("This is a QDial"))
        gb_lay.addWidget(Dial)
        m.setLayout(gb_lay)

        groupbox=QtWidgets.QGroupBox("This is a QGroupBox example with three QRadioButton")
        gb_lay=QtWidgets.QVBoxLayout()
        gb_lay.addWidget(QtWidgets.QRadioButton("1"))
        gb_lay.addWidget(QtWidgets.QRadioButton("2"))
        gb_lay.addWidget(QtWidgets.QRadioButton("3"))
        groupbox.setLayout(gb_lay)
        
        groupbox2=QtWidgets.QGroupBox("This is a QGroupBox example with three QCheckBox")
        gb_lay=QtWidgets.QVBoxLayout()
        gb_lay.addWidget(QtWidgets.QCheckBox("1"))
        gb_lay.addWidget(QtWidgets.QCheckBox("2"))
        gb_lay.addWidget(QtWidgets.QCheckBox("3"))
        groupbox2.setLayout(gb_lay)


        vlayout =QtWidgets.QVBoxLayout()
        vlayout.addWidget(a)
        vlayout.addWidget(b)
        vlayout.addWidget(c)
        vlayout.addWidget(d)
        vlayout.addWidget(e)
        vlayout.addWidget(f)
        vlayout.addWidget(g)
        vlayout.addWidget(h)
        vlayout.addWidget(i)
        vlayout.addWidget(j)
        vlayout.addWidget(k)
        vlayout.addWidget(l)
        vlayout.addWidget(m)
        vlayout.addWidget(groupbox)
        vlayout.addWidget(groupbox2)

        self.setGeometry(400,200,150,150)
        self.resize(700,400)
        self.setLayout(vlayout)
if __name__ =="__main__":
    app=QtWidgets.QApplication([])
    window=main_window()
    window.show()
    sys.exit(app.exec_())